### ISSUE TITLE
test nerve in condition where the blubber API is down or/and kubernetes API is down

### ISSUE THREAD

**Issue by unixfox** [bolt-rip/nerve#15]
Tests needed to be done before deploying on OCC box:

- [ ] Does nerve auto retry the request to the blubber API if the API is down?
- [ ] Can nerve still function properly if an error occurred due to the outage of the blubber API, and then it is back up?
- [x] Can nerve still function properly if an error occurred due to the outage of the Kubernetes API, and then it is back up?

**Comment by dentmaged** [comment]
If k8s fails to launch a private server, the user is sent an error in chat. They can keep typing `/private` until a server is successfully launched.

**Comment by unixfox** [comment]
@dentmaged still an issue

**Comment by unixfox** [comment]
How to replicate the first part and second part easily:
1. Shutdown the API, can be any fake HTTP server even if it's not the blubber API.
2. Start bungeecord
3. See the error in the logs
```
[15:46:18 ERROR]: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:261)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:644)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation$$Lambda$293/000000000000000000.call(Unknown Source)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:654)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:648)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation$$Lambda$328/000000000000000000.call(Unknown Source)
[15:46:18 ERROR]:       at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
[15:46:18 ERROR]:       at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
[15:46:18 ERROR]:       at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
[15:46:18 ERROR]:       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:648)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:643)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:416)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:307)
[15:46:18 ERROR]:       at rip.bolt.nerve.api.APIManager.getCurrentlyRunningMatches(APIManager.java:33)
[15:46:18 ERROR]:       at rip.bolt.nerve.managers.AutomoveManager$1.run(AutomoveManager.java:32)
[15:46:18 ERROR]:       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[15:46:18 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[15:46:18 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[15:46:18 ERROR]:       at java.lang.Thread.run(Thread.java:823)
[15:46:18 ERROR]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[15:46:18 ERROR]:       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[15:46:18 ERROR]:       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[15:46:18 ERROR]:       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[15:46:18 ERROR]:       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[15:46:18 ERROR]:       at java.net.Socket.connect(Socket.java:607)
[15:46:18 ERROR]:       at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[15:46:18 ERROR]:       at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[15:46:18 ERROR]:       at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[15:46:18 ERROR]:       at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[15:46:18 ERROR]:       at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[15:46:18 ERROR]:       at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[15:46:18 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
[15:46:18 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
[15:46:18 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
[15:46:18 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
[15:46:18 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
[15:46:18 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[15:46:18 ERROR]:       at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:371)
[15:46:18 ERROR]:       at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:259)
[15:46:18 ERROR]:       ... 20 more
```
4. Start the API / fake HTTP server
5. Nerve doesn't try again to communicate with the API

**Comment by dentmaged** [comment]
Fixed in https://github.com/bolt-rip/nerve/commit/eab80aa7f699ba6d835c160e4f1891c252195af1
